### ISSUE TITLE
Readme steps resulted in errors

### ISSUE THREAD

**Issue by dgannon991** [getporter/tofu-mixin#9]
When I attempted to build from source I received errors:
- No target for EnsureMage.
- mage install appeared to be a no-op until mage build was run.

**Comment by dgannon991** [comment]
Issue 2 turns out to be PEBKAC, sorry guys! Turns out I just skipped the step that said build :D

**Comment by kichristensen** [comment]
@dgannon991 Was this fixed by #10 ?

**Comment by dgannon991** [comment]
It was, sorry I didn't close this as well!
